### ISSUE TITLE
Application fails to start up

### ISSUE THREAD

**Issue by dereklin** [nydiarra/springboot-jwt#2]
I am on windows 10.

First, I had to delete the test file to make mvn clean package to work.

After that, I cd to target and ran java -jar springboot-jwt-0.0.1-SNAPSHOT.jar

I get

```
2017-10-15 11:15:02.503 ERROR 41860 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.NoClassDefFoundError: org/springframework/security/oauth2/client/DefaultOAuth2ClientContext
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_60]
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[na:1.8.0_60]
        at java.lang.Class.getDeclaredMethods(Unknown Source) ~[na:1.8.0_60]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:613) ~[spring-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:524) ~[spring-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:510) ~[spring-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
        at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:570) ~[spring-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
 ```

**Comment by dereklin** [comment]
Nevermind.  I had to clean up my maven cache.   Everything is working nicely.
